apiVersion: coolify/v1
kind: Project
metadata:
  name: elearning
  displayName: elearning
spec:
  runtime: docker
  server: main
  services:
    - name: app
      type: web
      port: 3000
      build:
        compose: docker-compose.yml
